### ISSUE TITLE
Basic implementation

### ISSUE THREAD

**Issue by firecorgi** [Trixwell/altSlider#1]
# **Additional work needs:**

* ~~Fix mark up.~~
* ~~Design fixes (CSS).~~
* ~~Add missed date.~~
* ~~Extra functions (gonna add features for handling data withtout using AJAX request)~~
* ~~Add support for dynamic reload of data (usinng  AJAX).~~
* ~~To add a function for scrolling 1 element per time while user click on it (similar to functionality of wheeling scroll).~~
* ~~Different variants of stylization (fonts, colors, etc.).~~
* ~~Elastic configuration: turn of scroll or scroll config, turn of AJAX requests.~~
* ~~JavaScript examples.~~
* ~~Add scroll stylization.~~
* ~~Add auto scroll mod.~~

**Comment by firecorgi** [comment]
1. Fixed mark up - DONE

**Comment by firecorgi** [comment]
2. Design fixes (CSS) -  DONE
6. To add a function for scrolling 1 element per time while user click on it (similar to functionality of wheeling scroll). - DONE

**Comment by firecorgi** [comment]
10. Add scroll stylization - DONE <333333

**Comment by firecorgi** [comment]
3. Add missed date. -  DONE

**Comment by firecorgi** [comment]
4. Additional functions (gonna add features for handling data withtout using AJAX request). - DONE

**Comment by firecorgi** [comment]
5.Add support for dynamic reload of data (usinng AJAX). - DONE

**Comment by firecorgi** [comment]
8.Elastic configuration: turn of scroll or scroll config, turn of AJAX requests. - DONE

**Comment by tptrixtop** [comment]
test ~~cross~~

**Comment by firecorgi** [comment]
Different variants of stylization (fonts, colors, etc.). -  DONE

**Comment by firecorgi** [comment]
Add auto scroll mod. - DONE
